/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by states
SELECT
    state_name,
    COUNT(customer_id) AS total_customers
FROM gold.dim_location
GROUP BY state_name
ORDER BY total_customers DESC;


-- Find total products by division
SELECT
    division,
    COUNT(product_id) AS total_products
FROM gold.dim_products
GROUP BY division
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
    division,
    AVG(unit_cost) AS avg_cost
FROM gold.dim_products
GROUP BY division
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT
    p.division,
    SUM(f.sales) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_id = f.product_id
GROUP BY p.division
ORDER BY total_revenue DESC;


-- What is the total revenue generated by each customer?
SELECT
    c.customer_id,
    SUM(f.sales) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_location c
    ON c.customer_id = f.customer_id
GROUP BY 
    c.customer_id
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    c.state_name,
    SUM(f.units) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_location c
    ON c.customer_id = f.customer_id
GROUP BY c.state_name
ORDER BY total_sold_items DESC;